Name:           ros-indigo-smarthome-common-driver
Version:        0.1.61
Release:        0%{?dist}
Summary:        ROS smarthome_common_driver package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rosjava-core
Requires:       ros-indigo-rosjava-dynamic-reconfigure
Requires:       ros-indigo-rosjava-messages
Requires:       ros-indigo-smarthome-comm-msgs-java
Requires:       ros-indigo-smarthome-heater-msgs-java
Requires:       ros-indigo-smarthome-media-msgs-java
Requires:       ros-indigo-smarthome-network-zeroconf
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rosjava-build-tools
BuildRequires:  ros-indigo-rosjava-core
BuildRequires:  ros-indigo-rosjava-dynamic-reconfigure
BuildRequires:  ros-indigo-rosjava-messages
BuildRequires:  ros-indigo-smarthome-comm-msgs-java
BuildRequires:  ros-indigo-smarthome-heater-msgs-java
BuildRequires:  ros-indigo-smarthome-media-msgs-java
BuildRequires:  ros-indigo-smarthome-network-zeroconf

%description
This package is Common interface for RosJava.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jun 05 2016 Mickaël Gaillard <mick.gaillard@gmail.com> - 0.1.61-0
- Autogenerated by Bloom

* Wed Jun 01 2016 Mickaël Gaillard <mick.gaillard@gmail.com> - 0.1.60-0
- Autogenerated by Bloom

